<script setup lang="ts">
import { ref } from 'vue'
import { useRouter, RouterLink } from 'vue-router'
import message from 'ant-design-vue/es/message'
import { ArrowRight, AtSign, LockKeyhole, UserRound } from '@lucide/vue'
import { useAuthStore } from '@/stores/auth'
const auth = useAuthStore(); const router = useRouter(); const loading = ref(false); const form = ref({ username: '', password: '', confirmPassword: '', email: '', displayName: '' })
async function submit() { if (form.value.username.length < 3 || form.value.password.length < 6) { message.warning('用户名至少 3 位，密码至少 6 位'); return }; if (form.value.password !== form.value.confirmPassword) { message.warning('两次输入的密码不一致'); return }; loading.value = true; try { await auth.register({ username: form.value.username, password: form.value.password, email: form.value.email || undefined, displayName: form.value.displayName || undefined }); message.success('账号创建成功'); router.replace('/') } catch (error) { message.error(error instanceof Error ? error.message : '注册失败，请稍后重试') } finally { loading.value = false } }
</script>
<template><main class="auth-page"><section class="auth-panel"><div class="auth-brand"><div class="brand-mark">I</div><div><strong>InsightHub</strong><span>智能研究工作台</span></div></div><div class="auth-heading"><div class="eyebrow">GET STARTED</div><h1>创建研究账号</h1><p>建立一个属于你的工作空间，开始沉淀可复用的洞察。</p></div><a-form layout="vertical" class="auth-form" @submit.prevent="submit"><a-form-item label="用户名" required><a-input v-model:value="form.username" size="large" placeholder="3-64 个字符"><template #prefix><UserRound :size="16" /></template></a-input></a-form-item><a-form-item label="显示名称"><a-input v-model:value="form.displayName" size="large" placeholder="团队中如何称呼你"><template #prefix><AtSign :size="16" /></template></a-input></a-form-item><a-form-item label="邮箱"><a-input v-model:value="form.email" size="large" placeholder="可选"><template #prefix><AtSign :size="16" /></template></a-input></a-form-item><div class="form-split"><a-form-item label="密码" required><a-input-password v-model:value="form.password" size="large" placeholder="至少 6 位"><template #prefix><LockKeyhole :size="16" /></template></a-input-password></a-form-item><a-form-item label="确认密码" required><a-input-password v-model:value="form.confirmPassword" size="large" placeholder="再次输入" /></a-form-item></div><a-button type="primary" size="large" block :loading="loading" html-type="submit">创建账号 <ArrowRight :size="16" /></a-button></a-form><div class="auth-footer">已有账号？<RouterLink to="/login">返回登录</RouterLink></div></section></main></template>
